version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backstreet
    volumes:
      - db_data:/var/lib/postgres

volumes:
  db_data:
    driver: local

